### ISSUE TITLE
Getting error in starting project: ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by gegobyte** [mschwarzmueller/nextjs-course-code#27]
Getting lots of errors after cloning the starter project and running `npm install` and then `npm run dev`

```
chinmaysarupria@Chinmays-MacBook-Pro nextjs-course-code % npm install

added 342 packages, and audited 343 packages in 7s

52 packages are looking for funding
  run `npm fund` for details

18 vulnerabilities (8 moderate, 9 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
chinmaysarupria@Chinmays-MacBook-Pro nextjs-course-code % npm run dev

> nextjs-course@0.1.0 dev
> next dev

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in /Users/chinmaysarupria/nextapps/nextjs-course-code/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.552 (/Users/chinmaysarupria/nextapps/nextjs-course-code/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11590)
    at __nccwpck_require__ (/Users/chinmaysarupria/nextapps/nextjs-course-code/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at Object.270 (/Users/chinmaysarupria/nextapps/nextjs-course-code/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:400)
    at __nccwpck_require__ (/Users/chinmaysarupria/nextapps/nextjs-course-code/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at Object.327 (/Users/chinmaysarupria/nextapps/nextjs-course-code/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:260)
    at __nccwpck_require__ (/Users/chinmaysarupria/nextapps/nextjs-course-code/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at Object.845 (/Users/chinmaysarupria/nextapps/nextjs-course-code/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:3733) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by wgfi110** [comment]
have you solved the problem?
